services:
  api:
    build: .
    container_name: ethusd_cp3_api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src

  streamlit:
    build: .
    container_name: ethusd_cp3_streamlit
    command: streamlit run app/streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app/src
    depends_on:
      - api
